import { library } from '@fortawesome/fontawesome-svg-core'
import { faFacebookF } from '@fortawesome/free-brands-svg-icons'
import { faComment, faThumbsUp, faThumbsDown, faFlag, faShare, faArrowUp, faCircleCheck, faFaceLaugh, faHeart, faMessage, faThumbTack, faBell, faBellSlash, faPlay, faPause, faGauge, faVolumeXmark, faVolumeHigh, faVolumeLow, faVolumeUp, faCog, faClose, faArrowLeft, faArrowRight, faEllipsisVertical, faPlus, faXmark, faCaretDown, faCaretUp, faFilter, faArrowDown, faSort, faMagnifyingGlass, faTable, faList, faColumns, faEllipsis, faEye, faImage, faStar, faShoppingBag, faCartShopping } from '@fortawesome/free-solid-svg-icons'

library.add(faArrowUp)
library.add(faArrowUp)
library.add(faArrowDown)
// library.add()
library.add(faComment)
library.add(faCaretDown)
library.add(faCaretDown)
library.add(faCaretUp)
library.add(faEllipsisVertical)
library.add(faFlag)
library.add(faFilter)
library.add(faThumbsUp)
library.add(faThumbsDown)
library.add(faList)
library.add(faMagnifyingGlass)
library.add(faPlus)
library.add(faShare)
library.add(faSort)
library.add(faTable)
library.add(faXmark)
library.add(faColumns)
library.add(faEllipsis)
library.add(faEye)
library.add(faImage)
library.add(faStar)
library.add(faShoppingBag)
library.add(faFacebookF)

// YouTube
library.add(faCircleCheck)
library.add(faFaceLaugh)
library.add(faHeart)
library.add(faMessage)
library.add(faThumbTack)
library.add(faBell)
library.add(faBellSlash)
library.add(faPlay)
library.add(faPause)
library.add(faGauge)
library.add(faVolumeUp)
library.add(faVolumeHigh)
library.add(faVolumeLow)
library.add(faVolumeXmark)
library.add(faCog)
library.add(faClose)
library.add(faArrowLeft)
library.add(faArrowRight)


// Ecommerce
library.add(faCartShopping)
